# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=skylake -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
MAKEOPTS="-j4"

# NOTE: This stage was built with the bindist Use flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C

GENTOO_MIRRORS="https://ftp.rnl.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfiles/ http://ftp.rnl.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfiles/ ftp://ftp.rnl.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfiles/ rsync://ftp.rnl.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfiles/"
USE="X elogind dbus pulseaudio alsa exif truetype unicode -systemd djvu pdf postscript javascript"
GRUB_PLATFORMS="efi-64"
ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"
INPUT_DEVICES="synaptics libinput evdev"
VIDEO_CARDS="intel nouveau nvidia"
PYTHON_TARGETS="python3_11"
PYTHON_SINGLE_TARGET="python3_11"
LUA_TARGETS="lua5-3 lua5-1 luajit"
LUA_SINGLE_TARGET="luajit"
